// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnionArchitecture.infrastructure;

#nullable disable

namespace OnionArchitecture.infrastructure.Migrations
{
    [DbContext(typeof(UserDBContext))]
    [Migration("20251017192755_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnionArchitecture.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("passwordHash")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("T_User", (string)null);
                });

            modelBuilder.Entity("OnionArchitecture.Domain.Entities.UserAccessFail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailCount")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("_locked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("lockedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("T_AccessFail", (string)null);
                });

            modelBuilder.Entity("OnionArchitecture.Domain.Entities.UserLoginHistory", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("T_UserLoginHistory", (string)null);
                });

            modelBuilder.Entity("OnionArchitecture.Domain.Entities.User", b =>
                {
                    b.OwnsOne("OnionArchitecture.Domain.Entities.ValueObject.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("RegionNumber")
                                .HasMaxLength(8)
                                .IsUnicode(false)
                                .HasColumnType("int");

                            b1.Property<string>("number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .IsUnicode(false)
                                .HasColumnType("varchar(20)");

                            b1.HasKey("UserId");

                            b1.ToTable("T_User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("OnionArchitecture.Domain.Entities.UserAccessFail", b =>
                {
                    b.HasOne("OnionArchitecture.Domain.Entities.User", "user")
                        .WithOne("UserAccessFail")
                        .HasForeignKey("OnionArchitecture.Domain.Entities.UserAccessFail", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("OnionArchitecture.Domain.Entities.UserLoginHistory", b =>
                {
                    b.OwnsOne("OnionArchitecture.Domain.Entities.ValueObject.PhoneNumber", "phoneNumber", b1 =>
                        {
                            b1.Property<long>("UserLoginHistoryid")
                                .HasColumnType("bigint");

                            b1.Property<int>("RegionNumber")
                                .HasMaxLength(8)
                                .IsUnicode(false)
                                .HasColumnType("int");

                            b1.Property<string>("number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .IsUnicode(false)
                                .HasColumnType("varchar(20)");

                            b1.HasKey("UserLoginHistoryid");

                            b1.ToTable("T_UserLoginHistory");

                            b1.WithOwner()
                                .HasForeignKey("UserLoginHistoryid");
                        });

                    b.Navigation("phoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("OnionArchitecture.Domain.Entities.User", b =>
                {
                    b.Navigation("UserAccessFail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
